{
    'name': 'Diligence Learning Packages',
    'version': '1.0.20',
    'summary': 'Learning packages, bundle access, community, coaching, and referrals',
    'category': 'Website/eLearning',
    'author': 'Project ADS',
    'license': 'LGPL-3',
    'depends': [
        'website_sale_slides',
        'crm',
        'website_forum',
        'account',
        'account_payment',
        'payment',
        'hr',
        'hr_attendance',
        'hr_holidays',
        'project',
        'mass_mailing',
        'website_mass_mailing',
    ],
    'data': [
        'security/diligence_learning_security.xml',
        'security/ir.model.access.csv',
        'data/diligence_learning_data.xml',
        'data/diligence_marketing_data.xml',
        'data/diligence_blog_data.xml',
        'data/package_shop_template.xml',
        'views/package_dynamic_snippet.xml',
        'views/product_template_views.xml',
        'views/product_website_templates.xml',
        'views/package_product_tile_templates.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/referral_views.xml',
        'views/settlement_views.xml',
        'views/affiliate_portal_templates.xml',
        'views/student_portal_templates.xml',
        'views/crm_lead_views.xml',
        'views/academic_views.xml',
        'views/slide_slide_views.xml',
        'views/quiz_views.xml',
        'views/session_views.xml',
        'views/certificate_report.xml',
        'views/reporting_views.xml',
        'views/management_dashboard_views.xml',
        'views/auth_signup_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'diligence_learning/static/src/js/diligence_multitype_quiz.js',
            'diligence_learning/static/src/xml/diligence_quiz.xml',
        ],
    },
    'installable': True,
    'post_init_hook': 'post_init_hook',
}
