{
    'name': 'Diligence Learning Packages',
    'version': '1.0.0',
    'summary': 'Learning packages, bundle access, community, coaching, and referrals',
    'category': 'Website/eLearning',
    'author': 'Project ADS',
    'license': 'LGPL-3',
    'depends': [
        'website_sale_slides',
        'crm',
        'website_forum',
        'account',
        'account_payment',
        'payment',
        'hr',
        'hr_attendance',
        'hr_holidays',
        'project',
    ],
    'data': [
        'security/diligence_learning_security.xml',
        'security/ir.model.access.csv',
        'data/diligence_learning_data.xml',
        'views/product_template_views.xml',
        'views/product_website_templates.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/referral_views.xml',
        'views/settlement_views.xml',
        'views/affiliate_portal_templates.xml',
        'views/student_portal_templates.xml',
        'views/crm_lead_views.xml',
        'views/academic_views.xml',
        'views/slide_slide_views.xml',
        'views/reporting_views.xml',
        'views/management_dashboard_views.xml',
    ],
    'installable': True,
}
