from . import product_template
from . import product_product
from . import res_partner
from . import referral
from . import crm_lead
from . import slide_channel_partner
from . import academic
from . import sale_order
from . import slide_slide
from . import session
from . import website_menu
from . import website
from . import quiz
from . import mandarin_content
from . import learning_activity
from . import payment_transaction
