from . import product_template
from . import website
from . import product_product
from . import res_partner
from . import referral
from . import crm_lead
from . import slide_channel_partner
from . import academic
from . import sale_order
from . import slide_slide
from . import session
