from odoo import api, fields, models


class DiligenceWebsiteMenu(models.Model):
    _inherit = 'website.menu'

    diligence_page_owned = fields.Boolean(
        string='Auto-created Page',
        default=False,
        copy=False,
        help='The page was created automatically when this menu was added.',
    )

    @api.model
    def save(self, website_id, data):
        """Create a page together with a newly-added Website Builder menu.

        Odoo normally saves a new menu first and leaves page creation to a
        second optional action. For this academy, a new internal menu should
        be immediately usable. Existing pages are reused, while genuinely new
        URLs receive an editable blank page. No URL is hardcoded here.
        """
        new_menu_ids = {
            values.get('id'): values
            for values in data.get('data', [])
            if isinstance(values.get('id'), str)
        }
        result = super().save(website_id, data)
        website = self.env['website'].browse(website_id).exists()
        if not website:
            return result

        for values in new_menu_ids.values():
            url = (values.get('url') or '').strip()
            if not url.startswith('/') or url.startswith('//') or '#' in url or '?' in url:
                continue

            menu = self.search([
                ('website_id', '=', website.id),
                ('name', '=', values.get('name')),
                ('url', '=', url),
            ], order='id desc', limit=1)
            if not menu or menu.page_id:
                continue

            page = self.env['website.page'].sudo().with_context(active_test=False).search([
                ('url', '=', url),
                ('website_id', 'in', [False, website.id]),
            ], limit=1)
            if page:
                menu.write({'page_id': page.id})
                continue

            # Do not replace an existing Odoo controller route with a CMS page.
            try:
                controller_exists = website.check_existing_page(url)
            except RuntimeError:
                # Website Builder calls this from an HTTP request. Keep the
                # ORM method safe for imports/tests where no request exists.
                controller_exists = False
            if controller_exists:
                continue

            created = website.new_page(
                name=menu.name,
                add_menu=False,
                template='website.default_page',
                page_values={
                    'url': url,
                    'website_published': True,
                },
            )
            page = self.env['website.page'].sudo().browse(created.get('page_id'))
            if page:
                menu.write({'page_id': page.id, 'diligence_page_owned': True})

        return result

    def unlink(self):
        """Remove only pages generated by the corresponding new menu."""
        # Include legacy Website Builder pages that were created before the
        # ownership flag existed. Keep filesystem-backed Odoo pages and the
        # homepage protected; custom tracked pages belong to their menu.
        owned_pages = self.mapped('page_id').sudo().filtered(lambda page: (
            page.website_id
            and page.track
            and not page.is_homepage
            and not page.view_id.arch_fs
        ))
        if owned_pages:
            owned_pages.unlink()
        # Deleting a page cascades its linked menu in Odoo. Re-browse the
        # recordset before delegating so already-cascaded menu IDs are ignored.
        return super(DiligenceWebsiteMenu, self.exists()).unlink()
