import time
from datetime import datetime, time as datetime_time

from odoo import _, api, fields, models
from odoo.exceptions import UserError


class DiligenceWhatsAppCampaign(models.Model):
    _name = 'diligence.whatsapp.campaign'
    _description = 'Diligence WhatsApp Bulk Campaign'
    _order = 'create_date desc'

    name = fields.Char(required=True)
    survey_id = fields.Many2one('survey.survey', string='Survey')
    survey_url = fields.Char(string='Survey URL', help='Use a public survey URL or a URL generated by your survey flow.')
    message_template = fields.Text(
        required=True,
        default='Halo %(name)s, silakan isi survey Diligence Academy: %(survey_url)s',
        help='Available placeholders: %(name)s and %(survey_url)s.',
    )
    partner_ids = fields.Many2many('res.partner', string='Recipients')
    line_ids = fields.One2many('diligence.whatsapp.campaign.line', 'campaign_id', string='Deliveries')
    state = fields.Selection([
        ('draft', 'Draft'),
        ('prepared', 'Prepared'),
        ('done', 'Processed'),
    ], default='draft', required=True, copy=False)
    pending_count = fields.Integer(compute='_compute_counts')
    sent_count = fields.Integer(compute='_compute_counts')
    error_count = fields.Integer(compute='_compute_counts')

    @api.depends('line_ids.state')
    def _compute_counts(self):
        for campaign in self:
            campaign.pending_count = len(campaign.line_ids.filtered(lambda line: line.state == 'pending'))
            campaign.sent_count = len(campaign.line_ids.filtered(lambda line: line.state == 'sent'))
            campaign.error_count = len(campaign.line_ids.filtered(lambda line: line.state == 'error'))

    def action_prepare(self):
        for campaign in self:
            if not campaign.partner_ids:
                raise UserError(_('Select at least one recipient.'))
            if not campaign.survey_url:
                raise UserError(_('Set the survey URL before preparing the campaign.'))
            service = self.env['diligence.whatsapp.service'].sudo()
            for partner in campaign.partner_ids.filtered('phone'):
                existing = campaign.line_ids.filtered(lambda line: line.partner_id == partner)
                if existing:
                    continue
                message = service.render_message(
                    campaign.message_template,
                    partner,
                    survey_url=campaign.survey_url,
                )
                self.env['diligence.whatsapp.campaign.line'].sudo().create({
                    'campaign_id': campaign.id,
                    'partner_id': partner.id,
                    'message': message,
                })
            campaign.state = 'prepared'
        return True

    def action_send(self):
        for campaign in self:
            if campaign.state == 'draft':
                campaign.action_prepare()
            params = self.env['ir.config_parameter'].sudo()
            batch_limit = max(1, int(params.get_param('diligence.whatsapp.campaign_batch_limit', '20')))
            daily_limit = max(1, int(params.get_param('diligence.whatsapp.daily_campaign_limit', '100')))
            delay = max(0, int(params.get_param('diligence.whatsapp.campaign_delay_seconds', '15')))
            error_threshold = max(1, int(params.get_param('diligence.whatsapp.campaign_error_threshold', '5')))
            today_start = fields.Datetime.to_string(datetime.combine(fields.Date.context_today(self), datetime_time.min))
            sent_today = self.env['diligence.whatsapp.campaign.line'].sudo().search_count([
                ('state', '=', 'sent'), ('sent_at', '>=', today_start),
            ])
            remaining_daily = max(0, daily_limit - sent_today)
            lines = campaign.line_ids.filtered(lambda line: line.state not in ('sent', 'skipped'))[:min(batch_limit, remaining_daily)]
            service = self.env['diligence.whatsapp.service'].sudo()
            consecutive_errors = 0
            for index, line in enumerate(lines):
                result = service.send_text(line.phone, line.message)
                sent = result.get('sent')
                state = 'sent' if sent else 'skipped' if result.get('skipped') else 'error'
                line.write({
                    'state': state,
                    'error_message': result.get('error') or False,
                    'sent_at': fields.Datetime.now() if sent else False,
                })
                if state == 'error':
                    consecutive_errors += 1
                    if consecutive_errors >= error_threshold:
                        break
                else:
                    consecutive_errors = 0
                if sent and delay and index < len(lines) - 1:
                    time.sleep(delay)
            if not campaign.line_ids.filtered(lambda line: line.state not in ('sent', 'skipped')):
                campaign.state = 'done'
        return True


class DiligenceWhatsAppCampaignLine(models.Model):
    _name = 'diligence.whatsapp.campaign.line'
    _description = 'Diligence WhatsApp Bulk Delivery'
    _order = 'create_date desc'

    campaign_id = fields.Many2one('diligence.whatsapp.campaign', required=True, ondelete='cascade', index=True)
    partner_id = fields.Many2one('res.partner', required=True, ondelete='restrict', index=True)
    phone = fields.Char(compute='_compute_phone', store=True)
    message = fields.Text(required=True)
    state = fields.Selection([
        ('pending', 'Pending'),
        ('sent', 'Sent'),
        ('skipped', 'Skipped'),
        ('error', 'Error'),
    ], default='pending', required=True, copy=False, index=True)
    sent_at = fields.Datetime(copy=False, readonly=True)
    error_message = fields.Char(copy=False, readonly=True)

    _recipient_uniq = models.Constraint(
        'unique(campaign_id, partner_id)',
        'A recipient can only be added once to a campaign.',
    )

    @api.depends('partner_id.phone')
    def _compute_phone(self):
        service = self.env['diligence.whatsapp.service']
        for line in self:
            line.phone = service.normalize_number(line.partner_id.phone) if line.partner_id else False

    def action_send(self):
        service = self.env['diligence.whatsapp.service'].sudo()
        for line in self.filtered(lambda record: record.state != 'sent'):
            result = service.send_text(line.phone, line.message)
            line.write({
                'state': 'sent' if result.get('sent') else 'skipped' if result.get('skipped') else 'error',
                'error_message': result.get('error') or False,
                'sent_at': fields.Datetime.now() if result.get('sent') else False,
            })
        return True
